name: HTML and CSS Validation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install html5validator

      - name: Validate HTML
        run: html5validator --root .

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install CSSLint
        run: npm install -g csslint

      - name: Run CSSLint
        run: csslint .
        continue-on-error: true
